#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/environment" ]]
then
  source "/home/ubuntu/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/environment'" >&2
  exit 1
fi
