#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-3.4.4/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-3.4.4/environment"
  exec rbs "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-3.4.4/environment'" >&2
  exit 1
fi
