#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-3.2.2/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-3.2.2/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-3.2.2/environment'" >&2
  exit 1
fi
